apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: myapp-secret
  namespace: default
spec:
  type: kv-v2
  mount: secret
  path: myapp
  destination:
    name: myapp-secret
    create: true
  vaultAuthRef: vault-auth
  refreshAfter: 10s